-- Seed tech news data
INSERT INTO public.tech_news (title, description, image_url, source_url, category, is_featured) VALUES
('Quantum Computing Breakthrough: IBM Unveils 1000-Qubit Processor', 'IBM has announced a major milestone in quantum computing with their new 1000-qubit processor, bringing practical quantum computing closer to reality.', 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800', 'https://techcrunch.com', 'Quantum Computing', true),
('SpaceX Successfully Tests Starship Lunar Landing System', 'SpaceX completed critical testing of the Starship lunar landing system, advancing NASA Artemis mission preparations.', 'https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?w=800', 'https://space.com', 'Space Technology', true),
('AI Revolutionizes Drug Discovery: New Cancer Treatment Found', 'Artificial intelligence has accelerated the discovery of a promising new cancer treatment, reducing research time from years to months.', 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800', 'https://nature.com', 'AI & Healthcare', true),
('Next-Gen Solar Panels Achieve 47% Efficiency Record', 'Researchers have developed solar cells with unprecedented 47% efficiency using perovskite-silicon tandem technology.', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800', 'https://sciencedaily.com', 'Renewable Energy', false),
('Neural Interface Enables Paralyzed Patient to Walk Again', 'A revolutionary brain-spine interface has restored mobility to a paralyzed patient, marking a historic advancement in neurotechnology.', 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800', 'https://wired.com', 'Neurotechnology', true),
('Breakthrough in Fusion Energy: Net Positive Achieved', 'Scientists have achieved sustained net-positive energy output in fusion reactions, bringing clean unlimited energy closer to reality.', 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800', 'https://newscientist.com', 'Energy', false),
('Revolutionary Biodegradable Electronics Developed', 'Engineers have created fully biodegradable electronic circuits that dissolve harmlessly in the environment after use.', 'https://images.unsplash.com/photo-1581092921461-7031e8fbc20c?w=800', 'https://ieee.org', 'Sustainability', false),
('5G Network Achieves 10 Gbps Speed in Real-World Tests', 'Telecommunications companies demonstrate practical 10 Gbps 5G speeds, enabling new applications in autonomous vehicles and AR.', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800', 'https://zdnet.com', 'Telecommunications', false);

-- Seed research articles
INSERT INTO public.research_articles (title, abstract, content, authors, keywords, category, image_url) VALUES
('Deep Learning Approaches for Autonomous Vehicle Navigation', 'This paper presents a comprehensive review of deep learning techniques applied to autonomous vehicle navigation systems, including perception, decision-making, and control modules.', 'Full content of the research paper covering CNN architectures, reinforcement learning for decision making, and sensor fusion techniques for reliable navigation in complex environments...', ARRAY['Dr. Sarah Chen', 'Prof. Michael Roberts', 'Dr. Raj Patel'], ARRAY['deep learning', 'autonomous vehicles', 'computer vision', 'reinforcement learning'], 'Artificial Intelligence', 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800'),
('Sustainable Materials for Next-Generation Aerospace Applications', 'A study on advanced composite materials with reduced environmental impact for use in aerospace structures, focusing on bio-based polymers and recyclable carbon fiber systems.', 'Comprehensive analysis of bio-composites, life cycle assessments, mechanical properties testing, and manufacturing processes for sustainable aerospace materials...', ARRAY['Dr. Emma Williams', 'Dr. James Liu', 'Prof. Maria Garcia'], ARRAY['aerospace', 'sustainable materials', 'composites', 'bio-polymers'], 'Materials Science', 'https://images.unsplash.com/photo-1517976487492-5750f3195933?w=800'),
('Quantum Machine Learning: A Survey of Algorithms and Applications', 'This survey covers the intersection of quantum computing and machine learning, examining quantum-enhanced algorithms and their potential applications in various domains.', 'Detailed exploration of quantum neural networks, variational quantum eigensolvers, quantum kernel methods, and applications in chemistry simulation, optimization, and cryptography...', ARRAY['Prof. David Kim', 'Dr. Lisa Wang', 'Dr. Alex Thompson'], ARRAY['quantum computing', 'machine learning', 'quantum algorithms', 'optimization'], 'Quantum Computing', 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800'),
('Advances in CRISPR Gene Editing for Therapeutic Applications', 'A review of recent developments in CRISPR-Cas9 technology for treating genetic disorders, including delivery methods, off-target effects, and clinical trial results.', 'In-depth analysis of CRISPR mechanisms, guide RNA design, delivery vectors, safety considerations, and promising clinical applications in treating genetic diseases...', ARRAY['Dr. Jennifer Brown', 'Prof. Robert Taylor', 'Dr. Amanda Wilson'], ARRAY['CRISPR', 'gene editing', 'therapeutic applications', 'genetic disorders'], 'Biotechnology', 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800'),
('Neuromorphic Computing: Brain-Inspired Hardware for AI', 'This paper explores neuromorphic computing architectures that mimic biological neural networks, offering energy-efficient alternatives to traditional computing for AI applications.', 'Examination of memristor-based systems, spiking neural networks, hardware implementations, and energy efficiency comparisons with conventional GPU-based AI systems...', ARRAY['Dr. Kevin Zhang', 'Prof. Susan Miller', 'Dr. Chris Anderson'], ARRAY['neuromorphic computing', 'artificial intelligence', 'spiking neural networks', 'energy efficiency'], 'Computer Architecture', 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800'),
('Renewable Energy Integration in Smart Grid Systems', 'A comprehensive study on integrating large-scale renewable energy sources into smart grid infrastructure, addressing challenges in stability, storage, and demand response.', 'Analysis of grid integration challenges, energy storage solutions, demand-side management, predictive algorithms, and case studies from successful implementations worldwide...', ARRAY['Dr. Patricia Lee', 'Prof. Mark Johnson', 'Dr. Daniel Brown'], ARRAY['smart grid', 'renewable energy', 'energy storage', 'grid stability'], 'Energy Systems', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800');

-- Seed announcements
INSERT INTO public.announcements (title, content, is_pinned) VALUES
('Welcome to TechEd Research Hub', 'Welcome to our new research and collaboration platform! Explore tech news, research articles, and connect with your guides and fellow students.', true),
('New AI Assistant Available', 'Our AI-powered assistant is now available to help you with your studies, research queries, and task management. Access it from the sidebar!', true),
('Research Paper Submission Deadline', 'Reminder: The deadline for submitting research papers for the Spring Conference is April 30th. Please ensure all submissions are complete.', false);
