# Generated by Django 6.0.4 on 2026-04-29 04:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('domain', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('IoT', 'Internet of Things')], max_length=50)),
                ('status', models.CharField(default='Pending Allocation', max_length=50)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('guide', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teams', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Synopsis', 'Synopsis'), ('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2'), ('Final Project Report', 'Final Project Report'), ('Publication Details', 'Publication Details')], max_length=50)),
                ('document', models.FileField(upload_to='milestones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'zip'])])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_rating', models.IntegerField(default=0)),
                ('coordinator_approval', models.BooleanField(default=False)),
                ('publication_status', models.BooleanField(default=False)),
                ('certificate_copy', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='projects.project')),
            ],
        ),
    ]
